# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'NameThatTruck' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for NameThatTruck
    pod 'SwiftyGif', '3.0.3'
    pod ‘Firebase/Core’

end
